#!/bin/fish

#Navegation
alias .. 'cd ..'
alias ... 'cd ../..'
alias .... 'cd ../../..'
alias setdir 'pwd > "$HOME/.local/data/saveddir"'
alias godir '[ -f "$HOME/.local/data/saveddir" ] && cd (cat "$HOME/.local/data/saveddir") || echo "Directory not setted!"'

#ls
alias la 'ls -a'
alias lt 'ls -alt'

#ssh
alias hoggar 'ssh -X -i ~/.ssh/hoggar paludo@hoggar.fisica.ufpr.br'
alias mhoggar 'sshfs -o allow_other -o IdentityFile=/home/nanni/.ssh/hoggar paludo@hoggar.fisica.ufpr.br:/home/jobs/paludo /home/nanni/pesquisa/hoggar'
alias umhoggar 'fusermount -z -u /home/nanni/pesquisa/hoggar'

#My programs
alias RU '$HOME/projects/dev/marcadorRU/marcadorRU.exe'
alias acoes 'ipython -i "$HOME/projects/dev/pyacoes/launch.py"'
alias noiselist 'docker-compose -f ~/.local/src/noiselist/docker-compose-prod.yml up'

#Git
abbr -ag g 'git'
abbr -ag ga 'git add'
abbr -ag gs 'git status'
abbr -ag gc 'git commit -m'
abbr -ag gd 'git diff'
abbr -ag gcl 'git clone'
abbr -ag gco 'git checkout'
abbr -ag gpl 'git pull'
abbr -ag gps 'git push'

#Encurtadores
abbr sdn 'sudo shutdown -h now'
abbr srn 'sudo shutdown -r now'
abbr dc  'docker-compose'
abbr dcr 'docker-compose run --rm'
abbr dcu 'docker-compose up'
abbr dcd 'docker-compose down'

#Facilitadores de memorização
alias html2pdf 'wkhtmltopdf'
alias autoopen 'xdg-open'
alias weather 'curl wttr.in'
alias volumemixer 'pulsemixer'

#Pacman
abbr -ag pc 'sudo pacman'
abbr -ag pi 'sudo pacman -Syu'
abbr -ag pr 'sudo pacman -Rcns'

#Outros
alias vi vim
if not test (command -v subl)
	alias subl 'subl3'
end
alias newterm 'pwd | st & disown'

#Custom functions
function cs
	cd $argv && ls
end

function za
	zathura $argv &
end
