#!/bin/bash


#Faz printar os processos que mais usam cpu quando clicado pelo mouse
case $BLOCK_BUTTON in
    1) notify-send "CPU Usage" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
    3) notify-send "CPU Usage" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)" ;;
esac


#Define limiares
limiar_warn=50;
limiar_crit=85;

#Acha cpu disponível
idle=$(mpstat | awk '/all/ {print $12}')

#Calcula cpu usado
cpu_usage=$(echo "100.0 - $idle" | bc)
cpu_usage_short=$(printf "%.1f" $cpu_usage)

#Imprime uso de cpu
echo " $cpu_usage_short%"
echo " $cpu_usage%"

#Imprime cor correspondente ao nível de uso
if (( $(echo "$cpu_usage > $limiar_crit.0" | bc) )); then
	#Cor nível crítico
	echo "#FF0000"
elif (( $(echo "$cpu_usage > $limiar_warn.0" | bc) )); then
	#Cor nível warn
	echo "#FFFC00"
else
	#Cor nível normal
	echo "#d0d0d0"
	# echo "#00ff7f"
fi


