#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


#Faz printar os processos que mais ocupam memória quando clicado pelo mouse
case $BLOCK_BUTTON in
	1) notify-send "Memory consumption" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	3) notify-send "Memory consumption" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
esac


#Acha valor em kilobytes da memória livre
freeMem_int=$(awk '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
END { printf(mem_free) }' /proc/meminfo)

#Valor em gigas da memória livre
freeMem=$(echo freeMem_int | awk -v x=$freeMem_int '{ printf("%.1f", x/1024/1024) }')

#Define limiares
limiarVermelho=1024*1024/2 #0.5Gb
limiarLaranja=1024*1024 #1.0Gb

#Define valores de cores
RED="#FF2005"
ORANGE="#FFF610"
GREEN="#10FF70"
WHITE="#D0D0D0"


#Checa se é necessário imprimir o valor da swap
if [[ $freeMem_int -lt $limiarVermelho ]]; then
	#Acha valor em kilobytes da memória livre
	freeSwap_int=$(awk '/^SwapFree:/ { printf($2) }' /proc/meminfo)
	
	#Converte para gigas
	freeSwap=$(echo freeSwap_int | awk -v x=$freeSwap_int '{ printf("%.1f", x/1024/1024) }')
fi


#Imprime valores da memória e cor
if [[ $freeMem_int -lt $limiarVermelho ]]; then
	echo $freeMem"G | Swap $freeSwap""G"
	echo $freeMem
	echo $RED
elif [[ $freeMem_int -lt $limiarLaranja ]]; then
	echo $freeMem'G'
	echo $freeMem
	echo $ORANGE
else
	echo $freeMem'G'
	echo $freeMem
	echo $WHITE
	#echo $GREEN
fi

